class Solution:
    def numDistinct(self, s: str, t: str) -> int:
        # state: dp[i][j] stores the number of ways to generate t[:j] with s[:i]
        dp = [[0] * (len(t) + 1) for _ in range(len(s) + 1)]

        # initialization
        # empty t can always be generated by deleting all chars in s[:i]
        for i in range(len(s) + 1):
            dp[i][0] = 1
        
        # transition function
        for i in range(1, len(s) + 1):
            for j in range(1, len(t) + 1):
                # case 1: don't use s[i - 1]
                dp[i][j] = dp[i - 1][j]
                # case 2: use s[i - 1] to match t[j - 1]
                if s[i - 1] == t[j - 1]:
                    dp[i][j] += dp[i - 1][j - 1]


        # answer
        return dp[len(s)][len(t)]